# Formato: login = hash_bcrypt_da_senha
admin = $2a$10$ARO.rSBwIz2UK0gUK47IMufScBH7l7.QDfnlvw71ehILQZNHnypmq
leandro = $2a$10$QsqUCTgue3HQvpHQHJez1.B3AV2GW4Pp4s9m1bnsIgNSjSEowRkzu
silvana = $2a$10$guNlkwlL.UwqXgxIaU4sVu0rP13zdUKmiBDV52rvmayeoBC0gIKs6
monica = $2a$10$Kc88huWxzLxaj5py02.GmOJUNRq/ICP/EPHxXL5uHASSS86Lq1KkS
ralph = $2a$10$kCZu/O1edCbvGGVtg3zaNuf6/P2abyYYViJWmTw23zWu4D5LxJpWC